# Lectura de ficheros con pandas

In [3]:
import pandas as pd

## Lectura de cora.content

In [4]:
# Leer archivo cora.content
# Según el README: <paper_id> <word_attributes>+ <class_label>
# The first entry in each line contains the unique string ID of the paper followed by binary values indicating whether each word in the vocabulary is present (indicated by 1) or absent (indicated by 0) in the paper. Finally, the last entry in the line contains the class label of the paper.

columnas = ['paper_id'] + [f'w{i}' for i in range(1433)] + ['clase']

papers = pd.read_csv('../data/cora.content',
                    sep='\t',          # separador tabulador
                    header = None,     # el fichero no tiene cabecera
                    names = columnas
                    )

papers['paper_id'] = papers['paper_id'].astype(str)

print(f'FILAS Y COLUMNAS DEL DATASET: {papers.shape}')

print('\nNÚMERO DE PAPERS POR CLASE:')
print(papers['clase'].value_counts())

print('\nPRIMEROS 2 PAPERS DEL DATASET:')
papers.head(2)

FILAS Y COLUMNAS DEL DATASET: (2708, 1435)

NÚMERO DE PAPERS POR CLASE:
clase
Neural_Networks           818
Probabilistic_Methods     426
Genetic_Algorithms        418
Theory                    351
Case_Based                298
Reinforcement_Learning    217
Rule_Learning             180
Name: count, dtype: int64

PRIMEROS 2 PAPERS DEL DATASET:

,paper_id,w0,w1,w2,w3,w4,w5,w6,w7,w8,...,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432,clase
0,31336,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1,1061127,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning

## Lectura de cora.cites

In [5]:
# Leer archivo cora.cites
# Según el README: <ID of cited paper> <ID of citing paper>
# Each line contains two paper IDs. The first entry is the ID of the paper being cited and the second ID stands for the paper which contains the citation. The direction of the link is from right to left. If a line is represented by "paper1 paper2" then the link is "paper2->paper1". 

citas = pd.read_csv('../data/cora.cites',
                    sep='\t',
                    header = None,
                    names = ['citado','citador']
                    )

citas = citas.astype(str)

print(f'FILAS Y COLUMNAS DEL DATASET: {citas.shape}')

print('\nPRIMERAS 5 CITAS DEL DATASET:')
citas.head()

FILAS Y COLUMNAS DEL DATASET: (5429, 2)

PRIMERAS 5 CITAS DEL DATASET:

  citado  citador
0     35     1033
1     35   103482
2     35   103515
3     35  1050679
4     35  1103960

## Codificación del atributo objetivo 'clase'

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
codificador_clase = LabelEncoder()
clases = papers['clase']

# Convertir etiquetas de texto a valores numéricos
clases = codificador_clase.fit_transform(clases)

print('CLASES DETECTADAS EN EL DATASET:')
print(codificador_clase.classes_)

# Mostrar correspondencia entre clases originales y valores numéricos
tabla_clases = pd.DataFrame({
    'CLASE ORIGINAL': codificador_clase.classes_,
    'CÓDIGO': range(len(codificador_clase.classes_)) # índice del array = número asignado a esa clase
})

print('\nTABLA DE CODIFICACIÓN DE CLASES:')
tabla_clases

CLASES DETECTADAS EN EL DATASET:
['Case_Based' 'Genetic_Algorithms' 'Neural_Networks'
 'Probabilistic_Methods' 'Reinforcement_Learning' 'Rule_Learning' 'Theory']

TABLA DE CODIFICACIÓN DE CLASES:

           CLASE ORIGINAL  CÓDIGO
0              Case_Based       0
1      Genetic_Algorithms       1
2         Neural_Networks       2
3   Probabilistic_Methods       3
4  Reinforcement_Learning       4
5           Rule_Learning       5
6                  Theory       6

In [8]:
# Hacemos una copia del dataset original para sustituir la nueva columna
papers_codificado = papers.copy()
papers_codificado['clase'] = clases

print('\nPRIMEROS 2 PAPERS CON CLASES CODIFICADAS:')
papers_codificado.head(2)

PRIMEROS 2 PAPERS CON CLASES CODIFICADAS:

,paper_id,w0,w1,w2,w3,w4,w5,w6,w7,w8,...,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432,clase
0,31336,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,2
1,1061127,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,5

# Construcción del grafo

In [9]:
import networkx as nx

In [10]:
G_directed = nx.DiGraph()

G_directed.add_nodes_from(papers['paper_id'])
G_directed.add_edges_from(zip(citas['citador'], citas['citado']))